;Bob the Bartender BG31_BOB
[BG31_BOBt4] ;Find a Triple
	points = 16.91
[BG31_BOBt3] ;Refresh the Tavern
	points = 5.51
[BG31_BOBt2] ;Recruit a Minion
	points = 8.46
[BG31_BOBt] ;Freeze the Shop
	points = 69.08
