;Bob the Bartender BG31_BOB
[BG31_BOBt4] ;Find a Triple
	points = 18.63
[BG31_BOBt3] ;Refresh the Tavern
	points = 6.01
[BG31_BOBt2] ;Recruit a Minion
	points = 8.58
[BG31_BOBt] ;Freeze the Shop
	points = 66.75
