;Bob the Bartender BG31_BOB
[BG31_BOBt4] ;Find a Triple
	points = 22.11
[BG31_BOBt3] ;Refresh the Tavern
	points = 7.33
[BG31_BOBt2] ;Recruit a Minion
	points = 12.25
[BG31_BOBt] ;Freeze the Shop
	points = 58.27
