;Arthas's Gift GIFT_04
[RLK_024] ;Death Strike
	points = 48.87
[RLK_015] ;Howling Blast
	points = 33.76
[RLK_057] ;Dark Transformation
	points = 17.41
[TIME_000tb] ;Rewind Timeline
	points = 0
