;Bob the Bartender BG31_BOB
[BG31_BOBt4] ;Find a Triple
	points = 9.79
[BG31_BOBt3] ;Refresh the Tavern
	points = 14.32
[BG31_BOBt2] ;Recruit a Minion
	points = 4.32
[BG31_BOBt] ;Freeze the Shop
	points = 71.54
[TIME_101] ;Misplaced Pyromancer
	points = 6.06
[CFM_039] ;Street Trickster
	points = 9.37
[EDR_254] ;Animated Moonwell
	points = 16.12
[DINO_419] ;Herbivore Assistant
	points = 23.33
[TIME_046] ;Cyborg Patriarch
	points = 16.66
[EDR_001] ;Hopeful Dryad
	points = 65.51
[TLC_256] ;Marshland Thresher
	points = 27.58
[TLC_109] ;Relic Miner
	points = 17.85
[TSC_926] ;Smothering Starfish
	points = 39.28
[WON_141] ;Menagerie Mug
	points = 21.42
[TLC_888] ;Cloud Serpent
	points = 17.85
[TIME_053] ;Sandmaw
	points = 7.14
[TIME_045] ;Whelp of the Infinite
	points = 82.14
[TTN_859] ;Fate Splitter
	points = 59.25
[TIME_102] ;Circadiamancer
	points = 62.96
[TTN_733] ;Relentless Worg
	points = 30.76
[TIME_434] ;Temporal Traveler
	points = 57.69
[TSC_646] ;Seascout Operator
	points = 7.69
[TLC_101] ;Undercover Cultist
	points = 61.53
[TSC_013] ;Slimescale Diver
	points = 57.69
[TLC_251] ;Primalfin Challenger
	points = 3.84
[DINO_410] ;The Egg of Khelos
	points = 20
[TLC_242] ;Ancient Stegodon
	points = 32
[EDR_950] ;Sharp-Eyed Lookout
	points = 36
[TSC_938] ;Treasure Guard
	points = 56
[EDR_571] ;Fae Trickster
	points = 32
[TLC_253] ;Petrified Ogre
	points = 12
[CORE_EDR_004] ;Raptor Herald
	points = 45.83
[TIME_060] ;Quantum Destabilizer
	points = 12.5
[TSC_960] ;Twin-fin Fin Twin
	points = 37.5
[TLC_252] ;Dissolving Ooze
	points = 17.39
[EDR_598] ;Dream Rager
	points = 4.34
[TTN_718] ;Starlight Whelp
	points = 52.17
[TTN_731] ;Careless Mechanist
	points = 18.18
[TSC_640] ;Reefwalker
	points = 54.54
[TTN_712] ;Sharp-Eyed Seeker
	points = 13.63
[WON_139] ;Timeline Accelerator
	points = 0
[WON_357] ;Acolyte of Pain
	points = 19.04
[TTN_832] ;Trogg Exile
	points = 30
[TLC_465] ;Stranglevine
	points = 45
[TTN_924] ;Razorscale
	points = 15
[TTN_042] ;Cyclopian Crusher
	points = 63.15
[TSC_826] ;Crushclaw Enforcer
	points = 10.52
[TTN_734] ;Mecha-Leaper
	points = 10.52
[TID_710] ;Snapdragon
	points = 42.1
[EDR_780] ;Bloodthistle Illusionist
	points = 47.36
[TIME_056] ;Whelp of the Bronze
	points = 73.68
[TSC_002] ;Pufferfist
	points = 29.41
[TTN_729] ;Melted Maker
	points = 5.88
[TTN_754] ;Ravenous Kraken
	points = 18.75
[TIME_003] ;Portal Vanguard
	points = 37.5
