;Bob the Bartender BG31_BOB
[BG31_BOBt4] ;Find a Triple
	points = 9.78
[BG31_BOBt3] ;Refresh the Tavern
	points = 15.25
[BG31_BOBt2] ;Recruit a Minion
	points = 4.14
[BG31_BOBt] ;Freeze the Shop
	points = 70.72
[TTN_754] ;Ravenous Kraken
	points = 16.12
[TSC_646] ;Seascout Operator
	points = 3.22
[TIME_102] ;Circadiamancer
	points = 51.61
[EDR_001] ;Hopeful Dryad
	points = 72.41
[TTN_734] ;Mecha-Leaper
	points = 10.71
[CFM_039] ;Street Trickster
	points = 3.57
[TLC_252] ;Dissolving Ooze
	points = 14.81
[TTN_731] ;Careless Mechanist
	points = 33.33
[TID_710] ;Snapdragon
	points = 46.15
[TIME_053] ;Sandmaw
	points = 7.69
[EDR_950] ;Sharp-Eyed Lookout
	points = 24
[TSC_640] ;Reefwalker
	points = 44
[TIME_059] ;Living Paradox
	points = 32
[TLC_109] ;Relic Miner
	points = 12
[CORE_EDR_004] ;Raptor Herald
	points = 76
[TLC_101] ;Undercover Cultist
	points = 72
[DINO_410] ;The Egg of Khelos
	points = 25
[TLC_831] ;Pterrordax Egg
	points = 4.16
[TLC_242] ;Ancient Stegodon
	points = 50
[TIME_045] ;Whelp of the Infinite
	points = 87.5
[TIME_000tb] ;Rewind Timeline
	points = 47.82
[TTN_832] ;Trogg Exile
	points = 26.08
[EDR_571] ;Fae Trickster
	points = 17.39
[TTN_042] ;Cyclopian Crusher
	points = 40.9
[TLC_465] ;Stranglevine
	points = 27.27
[TTN_729] ;Melted Maker
	points = 0
[TSC_926] ;Smothering Starfish
	points = 45.45
[TIME_060] ;Quantum Destabilizer
	points = 31.81
[TSC_960] ;Twin-fin Fin Twin
	points = 61.9
[TSC_938] ;Treasure Guard
	points = 52.38
[TTN_712] ;Sharp-Eyed Seeker
	points = 4.76
[TTN_718] ;Starlight Whelp
	points = 47.61
[TIME_063] ;Timelord Nozdormu
	points = 28.57
[TIME_101] ;Misplaced Pyromancer
	points = 4.76
[WON_141] ;Menagerie Mug
	points = 28.57
[EDR_780] ;Bloodthistle Illusionist
	points = 42.85
[EDR_598] ;Dream Rager
	points = 10
[TTN_924] ;Razorscale
	points = 5
[EDR_254] ;Animated Moonwell
	points = 20
[DINO_419] ;Herbivore Assistant
	points = 10
[TIME_056] ;Whelp of the Bronze
	points = 50
[TLC_888] ;Cloud Serpent
	points = 55
[WON_357] ;Acolyte of Pain
	points = 25
[WON_139] ;Timeline Accelerator
	points = 10
[TTN_733] ;Relentless Worg
	points = 42.1
[TLC_251] ;Primalfin Challenger
	points = 10.52
[TLC_256] ;Marshland Thresher
	points = 42.1
[TIME_434] ;Temporal Traveler
	points = 55.55
[TSC_002] ;Pufferfist
	points = 38.88
[TIME_046] ;Cyborg Patriarch
	points = 17.64
[TIME_003] ;Portal Vanguard
	points = 35.29
[TTN_859] ;Fate Splitter
	points = 35.29
[TLC_253] ;Petrified Ogre
	points = 6.25
[TSC_013] ;Slimescale Diver
	points = 57.14
